/**
 * AIDEV-NOTE: Dicionário estático de correções ortográficas PT-BR
 * Mapa de palavras sem acento (lowercase) → sugestões com acento
 * Foco em acentuação — as correções mais comuns do dia a dia
 * Performance: O(1) lookup via hashmap
 */

export const CORRECOES_PT_BR: Record<string, string[]> = {
  // Verbos e palavras muito frequentes
  'nao': ['não'],
  'sao': ['são'],
  'voce': ['você'],
  'voces': ['vocês'],
  'tambem': ['também'],
  'entao': ['então'],
  'ja': ['já'],
  'ate': ['até'],
  'so': ['só'],
  'esta': ['está', 'esta'],
  'estao': ['estão'],
  'sera': ['será'],
  'serao': ['serão'],
  'nos': ['nós'],
  'ai': ['aí'],
  'alem': ['além'],
  'porem': ['porém'],
  'alias': ['aliás'],
  'atras': ['atrás'],
  'tres': ['três'],
  'apos': ['após'],
  'atraves': ['através'],
  

  // Substantivos comuns
  'informacao': ['informação'],
  'informacoes': ['informações'],
  'obrigacao': ['obrigação'],
  'obrigacoes': ['obrigações'],
  'comunicacao': ['comunicação'],
  'situacao': ['situação'],
  'opcao': ['opção'],
  'opcoes': ['opções'],
  'solucao': ['solução'],
  'solucoes': ['soluções'],
  'reuniao': ['reunião'],
  'reunioes': ['reuniões'],
  'orcamento': ['orçamento'],
  'orcamentos': ['orçamentos'],
  'negocio': ['negócio'],
  'negocios': ['negócios'],
  'servico': ['serviço'],
  'servicos': ['serviços'],
  'preco': ['preço'],
  'precos': ['preços'],
  'numero': ['número'],
  'numeros': ['números'],
  'horario': ['horário'],
  'horarios': ['horários'],
  'calendario': ['calendário'],
  'relatorio': ['relatório'],
  'relatorios': ['relatórios'],
  'periodo': ['período'],
  'comercio': ['comércio'],
  'inicio': ['início'],
  'pagina': ['página'],
  'paginas': ['páginas'],
  'codigo': ['código'],
  'codigos': ['códigos'],
  'titulo': ['título'],
  'titulos': ['títulos'],
  'analise': ['análise'],
  'area': ['área'],
  'areas': ['áreas'],
  'noticia': ['notícia'],
  'noticias': ['notícias'],
  'historia': ['história'],
  'historias': ['histórias'],
  'experiencia': ['experiência'],
  'experiencias': ['experiências'],
  'presenca': ['presença'],
  'frequencia': ['frequência'],
  'gerencia': ['gerência'],
  'referencia': ['referência'],
  'preferencia': ['preferência'],
  'sugestao': ['sugestão'],
  'sugestoes': ['sugestões'],
  'producao': ['produção'],
  'promocao': ['promoção'],
  'promocoes': ['promoções'],
  'educacao': ['educação'],
  'operacao': ['operação'],
  'operacoes': ['operações'],
  'organizacao': ['organização'],
  'organizacoes': ['organizações'],
  'apresentacao': ['apresentação'],
  'aplicacao': ['aplicação'],
  'aplicacoes': ['aplicações'],
  'contribuicao': ['contribuição'],
  'contribuicoes': ['contribuições'],
  'avaliacao': ['avaliação'],
  'avaliacoes': ['avaliações'],
  'configuracao': ['configuração'],
  'configuracoes': ['configurações'],
  'descricao': ['descrição'],
  'inscricao': ['inscrição'],
  'inscricoes': ['inscrições'],
  'atencao': ['atenção'],
  'prevencao': ['prevenção'],
  'funcao': ['função'],
  'funcoes': ['funções'],
  'acao': ['ação'],
  'acoes': ['ações'],
  'conexao': ['conexão'],
  'conexoes': ['conexões'],
  'posicao': ['posição'],
  'posicoes': ['posições'],
  'condicao': ['condição'],
  'condicoes': ['condições'],
  'excecao': ['exceção'],
  'excecoes': ['exceções'],
  'populacao': ['população'],
  'transacao': ['transação'],
  'transacoes': ['transações'],
  'versao': ['versão'],
  'versoes': ['versões'],
  'sessao': ['sessão'],
  'sessoes': ['sessões'],
  'comissao': ['comissão'],
  'comissoes': ['comissões'],

  // Adjetivos
  'necessario': ['necessário'],
  'necessaria': ['necessária'],
  'possivel': ['possível'],
  'impossivel': ['impossível'],
  'disponivel': ['disponível'],
  'responsavel': ['responsável'],
  'favoravel': ['favorável'],
  'provavel': ['provável'],
  'util': ['útil'],
  'facil': ['fácil'],
  'dificil': ['difícil'],
  'rapido': ['rápido'],
  'rapida': ['rápida'],
  'otimo': ['ótimo'],
  'otima': ['ótima'],
  'pessimo': ['péssimo'],
  'pessima': ['péssima'],
  'ultimo': ['último'],
  'ultima': ['última'],
  'proximo': ['próximo'],
  'proxima': ['próxima'],
  'unico': ['único'],
  'unica': ['única'],
  'publico': ['público'],
  'publica': ['pública'],
  'pratico': ['prático'],
  'pratica': ['prática'],
  'tecnico': ['técnico'],
  'tecnica': ['técnica'],
  'basico': ['básico'],
  'basica': ['básica'],
  'especifico': ['específico'],
  'especifica': ['específica'],
  'economico': ['econômico'],
  'economica': ['econômica'],
  'automatico': ['automático'],
  'automatica': ['automática'],
  'obrigatorio': ['obrigatório'],
  'obrigatoria': ['obrigatória'],
  'temporario': ['temporário'],
  'temporaria': ['temporária'],
  'voluntario': ['voluntário'],
  'voluntaria': ['voluntária'],

  // Advérbios e conectores
  'consequencia': ['consequência'],
  'consequencias': ['consequências'],
  'evidencia': ['evidência'],
  'eficiencia': ['eficiência'],
  'existencia': ['existência'],
  'influencia': ['influência'],
  'ausencia': ['ausência'],

  // Verbos conjugados comuns
  'tera': ['terá'],
  'terao': ['terão'],
  'fara': ['fará'],
  'farao': ['farão'],
  'dara': ['dará'],
  'darao': ['darão'],
  'ira': ['irá'],
  'irao': ['irão'],
  'vira': ['virá'],
  'virao': ['virão'],
  'podera': ['poderá'],
  'poderao': ['poderão'],
  'devera': ['deverá'],
  'deverao': ['deverão'],
  'ficara': ['ficará'],
  'ficarao': ['ficarão'],
  'precisara': ['precisará'],
  'comecara': ['começará'],
  'continuara': ['continuará'],
  'recebera': ['receberá'],
  'receberao': ['receberão'],
  'conseguira': ['conseguirá'],
  'conseguirao': ['conseguirão'],
  'estara': ['estará'],
  'estarao': ['estarão'],
  'comeco': ['começo'],
  'almoco': ['almoço'],

  // Saudações e expressões
  'bencao': ['bênção'],
  'parabens': ['parabéns'],

  // Dias e meses
  'sabado': ['sábado'],
  'segunda-feira': ['segunda-feira'],
  'terca': ['terça'],
  'terca-feira': ['terça-feira'],

  // Palavras comerciais/CRM
  'credito': ['crédito'],
  'creditos': ['créditos'],
  'debito': ['débito'],
  'debitos': ['débitos'],
  'catalogo': ['catálogo'],
  'catalogos': ['catálogos'],
  'logistica': ['logística'],
  'diagnostico': ['diagnóstico'],
  'estrategia': ['estratégia'],
  'estrategias': ['estratégias'],
  'politica': ['política'],
  'politicas': ['políticas'],
  'proposito': ['propósito'],
  'beneficio': ['benefício'],
  'beneficios': ['benefícios'],
  'patrimonio': ['patrimônio'],
  'formulario': ['formulário'],
  'formularios': ['formulários'],
  'dominio': ['domínio'],
  'dominios': ['domínios'],
  'ministerio': ['ministério'],

  // Palavras com til (ã/õ)
  'amanha': ['amanhã'],
  'manha': ['manhã'],
  'irma': ['irmã'],
  'irmao': ['irmão'],
  'irmaos': ['irmãos'],
  'mae': ['mãe'],
  'pao': ['pão'],
  'paes': ['pães'],
  'chao': ['chão'],
  'mao': ['mão'],
  'maos': ['mãos'],
  'cidadao': ['cidadão'],
  'cidadaos': ['cidadãos'],
  'capitao': ['capitão'],
  'alemao': ['alemão'],
  'coracao': ['coração'],
  'coracoes': ['corações'],
  'razao': ['razão'],
  'razoes': ['razões'],
  'estacao': ['estação'],
  'estacoes': ['estações'],
  'relacao': ['relação'],
  'relacoes': ['relações'],
  'licao': ['lição'],
  'licoes': ['lições'],
  'eleicao': ['eleição'],
  'eleicoes': ['eleições'],
  'regiao': ['região'],
  'regioes': ['regiões'],
  'natacao': ['natação'],
  'alimentacao': ['alimentação'],
  'atribuicao': ['atribuição'],
  'motivacao': ['motivação'],
  'negociacao': ['negociação'],
  'negociacoes': ['negociações'],
  'autorizacao': ['autorização'],
  'intencao': ['intenção'],
  'intencoes': ['intenções'],
  'mencao': ['menção'],
  'dimensao': ['dimensão'],
  'pensao': ['pensão'],
  'pressao': ['pressão'],
  'expressao': ['expressão'],
  'impressao': ['impressão'],
  'permissao': ['permissão'],
  'discussao': ['discussão'],
  'profissao': ['profissão'],
  'missao': ['missão'],
  'visao': ['visão'],
  'decisao': ['decisão'],
  'televisao': ['televisão'],
  'divisao': ['divisão'],
  'precisao': ['precisão'],
  'ocasiao': ['ocasião'],
  'opiniao': ['opinião'],
  'uniao': ['união'],
  'correcao': ['correção'],

  // Acentos agudos/circunflexos
  'cafe': ['café'],
  'pe': ['pé'],
  'fe': ['fé'],
  'saude': ['saúde'],
  'conteudo': ['conteúdo'],
  'conteudos': ['conteúdos'],
  'incluido': ['incluído'],
  'construido': ['construído'],
  'destruido': ['destruído'],
  'juizo': ['juízo'],
  'pais': ['país'],
  'agua': ['água'],
  'aguia': ['águia'],
  'obstaculo': ['obstáculo'],
  'veiculo': ['veículo'],
  'veiculos': ['veículos'],
  'musica': ['música'],
  'musicas': ['músicas'],
  'medico': ['médico'],
  'medica': ['médica'],
  'juridico': ['jurídico'],
  'juridica': ['jurídica'],
  'valido': ['válido'],
  'valida': ['válida'],
  'solido': ['sólido'],
  'liquido': ['líquido'],
  'individuo': ['indivíduo'],
  'habito': ['hábito'],
  'agradavel': ['agradável'],
  'saudavel': ['saudável'],
  'amavel': ['amável'],
  'notavel': ['notável'],
  'terrivel': ['terrível'],
  'incrivel': ['incrível'],
  'flexivel': ['flexível'],
  'acessivel': ['acessível'],
  'compativel': ['compatível'],
  'sustentavel': ['sustentável'],
  'rentavel': ['rentável'],

  // Abreviaturas comuns de chat/WhatsApp
  'vc': ['você'],
  'vcs': ['vocês'],
  'tb': ['também'],
  'tbm': ['também'],
  // AIDEV-NOTE: 'pq' removido — tratado pela lógica contextual em porques-contexto.ts
  'cmg': ['comigo'],
  'ctg': ['contigo'],
  'msg': ['mensagem'],
  'msgs': ['mensagens'],
  'qdo': ['quando'],
  'qto': ['quanto'],
  'qts': ['quantos'],
  'hj': ['hoje'],
  'dps': ['depois'],
  'blz': ['beleza'],
  'obg': ['obrigado'],
  'vlw': ['valeu'],
  'pfv': ['por favor'],
  'td': ['tudo'],
  'tds': ['todos'],
  'ngm': ['ninguém'],
  'agr': ['agora'],
  'msm': ['mesmo'],
  'qse': ['quase'],
  'mto': ['muito'],
  'mta': ['muita'],
  'tmj': ['tamo junto'],
  'flw': ['falou'],
  'abs': ['abraços'],
  'bjs': ['beijos'],
  'pls': ['por favor'],
  'add': ['adicionar'],
  'info': ['informação'],
  'ref': ['referência'],

  // Novas abreviações de chat (vícios de linguagem)
  'oq': ['o que'],
  'oqe': ['o que'],
  'kd': ['cadê'],
  'cad': ['cadê'],
  'qnd': ['quando'],
  'qnto': ['quanto'],
  'mtu': ['muito'],
  'tmb': ['também'],
  'nd': ['nada'],
  'nda': ['nada'],
  'qlqr': ['qualquer'],
  'qq': ['qualquer'],
  'dnv': ['de novo'],
  'smp': ['sempre'],
  'sdds': ['saudades'],
  'sdd': ['saudades'],
  'sla': ['sei lá'],
  'vdd': ['verdade'],
  'pse': ['pois é'],
  'pdc': ['pode crer'],
  'btf': ['boto fé'],
  'mds': ['meu Deus'],
  'ft': ['foto'],
  'ctt': ['contato'],
  'amh': ['amanhã'],

  // Erros ortográficos comuns em chat
  'eh': ['é'],
  'nivel': ['nível'],
  'benvindo': ['bem-vindo'],
}
